---
image: maven:3-jdk-11

stages:
  - build
  - test

build-job-ubuntu:
  stage: build

  tags: [ ]
  script: "mvn clean install -D=skipTests"

test-job-unit-ubuntu:
  stage: test
  needs: [ "build-job-ubuntu" ]

  tags: [ ]
  script: "mvn test '-Dtest=!*TestIT*'"

build-job-windows:
  stage: build

  tags: [ shared-windows ]
  script: "echo %JAVA_HOME%"

test-unit-windows:
  stage: test
  needs: [ "build-job-windows" ]

  tags: [ shared-windows ]
  script: "echo %JAVA_HOME%"