version: 2.1

jobs:
  build-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13

    steps:
      - checkout
      - run:
          name: Build with Maven on Ubuntu
          command: mvn clean install -D=skipTests

  unit-test-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13

    steps:
      - checkout
      - run:
          name: Unit tests with Maven
          command: mvn test '-Dtest=!*TestIT*'

  test-IT-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13
        environment:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/restaurant
          JDBC_DATABASE_USERNAMEL: postgres
          JDBC_DATABASE_PASSWORD: admin

      - image: cimg/postgres:14.1
        environment:
          POSTGRES_DB: restaurant

    steps:
      - checkout
      - run:
          name: Integration tests with Maven
          command: mvn test '-Dtest=*TestIT*'

  test-all-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13
        environment:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/restaurant
          JDBC_DATABASE_USERNAMEL: postgres
          JDBC_DATABASE_PASSWORD: admin

      - image: cimg/postgres:14.1
        environment:
          POSTGRES_DB: restaurant

    steps:
      - checkout
      - run:
          name: All tests with Maven
          command: mvn test '-Dtest=*Test*'

workflows:
  build_and_test:
    jobs:
      - build-ubuntu

      - unit-test-ubuntu:
          requires:
            - build-ubuntu

      - test-IT-ubuntu:
          requires:
            - unit-test-ubuntu

      - test-all-ubuntu:
          requires:
            - test-IT-ubuntu
