version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  build-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13

    steps:
      - checkout
      - run:
          name: Build with Maven on Ubuntu
          command: mvn clean install -D=skipTests

  build-windows:

    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run:
          name: Install maven
          command: choco install maven
      - run:
          name: Build with Maven on Ubuntu
          command: mvn clean install -D=skipTests

  unit-test-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13

    steps:
      - checkout
      - run:
          name: Unit tests with Maven
          command: mvn test '-Dtest=!*TestIT*'

  unit-test-windows:

    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run:
          name: Install maven
          command: choco install maven
      - run:
          name: Unit tests with Maven
          command: mvn test '-Dtest=!*TestIT*'

  test-IT-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13
        environment:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/restaurant
          JDBC_DATABASE_USERNAMEL: postgres
          JDBC_DATABASE_PASSWORD: admin

      - image: cimg/postgres:14.1
        environment:
          POSTGRES_DB: restaurant

    steps:
      - checkout
      - run:
          name: Integration tests with Maven
          command: mvn test '-Dtest=*TestIT*'

  test-all-ubuntu:

    docker:
      - image: cimg/openjdk:11.0.13
        environment:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/restaurant
          JDBC_DATABASE_USERNAMEL: postgres
          JDBC_DATABASE_PASSWORD: admin

      - image: cimg/postgres:14.1
        environment:
          POSTGRES_DB: restaurant

    steps:
      - checkout
      - run:
          name: All tests with Maven
          command: mvn test '-Dtest=*Test*'

workflows:
  build_and_test:
    jobs:
      - build-ubuntu
      - build-windows

      - unit-test-ubuntu:
          requires:
            - build-ubuntu

      - unit-test-windows:
          requires:
            - build-windows

      - test-IT-ubuntu:
          requires:
            - unit-test-ubuntu
            - unit-test-windows

      - test-all-ubuntu:
          requires:
            - test-IT-ubuntu

  #  build-macOS:
  #
  #    macos:
  #      xcode: 12.5.1
  #
  #    steps:
  #      - checkout
  #      - run:
  #          name: Install OpenJDK 11
  #          command: |
  #            sudo apt-get update && sudo apt-get install openjdk-11-jdk
  #            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
  #            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
  #            java -version
  #      - run:
  #          name: Build with Maven on Ubuntu
  #          command: mvn clean install -D=skipTests
