image: maven:3-jdk-11

variables:
  POSTGRES_DB: restaurant
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin

stages:
  - build
  - test

compile:
  stage: .pre

  script: "mvn compile"

sonarcloud-analysis:
  stage: build

  needs: [ "compile" ]

  script:
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=damman96_RestaurantManager

build-job:
  stage: build

  needs: [ "compile" ]

  script: "mvn clean install -D=skipTests"

unit-tests-job:
  stage: test
  needs: [ "build-job" ]

  script: "mvn test '-Dtest=!*TestIT*'"

IT-tests-job:
  stage: test
  needs: [ "build-job", "unit-tests-job" ]

  services:
    - postgres:latest

  script: "mvn test '-Dtest=*TestIT*' '-Dspring.profiles.active=gitlab'"

all-tests-job:
  stage: test
  needs: [ "build-job", "unit-tests-job", "IT-tests-job" ]

  services:
    - postgres:latest

  script: "mvn test '-Dtest=*Test*' '-Dspring.profiles.active=gitlab'"
