image: maven:3-jdk-11

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - build
  - test

compile:
  stage: .pre

  script: "mvn compile"

sonarcloud-analysis:
  stage: build

  needs: [ "compile" ]

  script:
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=damman96_RestaurantManager

build-job:
  stage: build

  needs: [ "compile" ]

  script: "mvn clean install -D=skipTests"

test-job-unit:
  stage: test
  needs: [ "build-job" ]

  script: "mvn test '-Dtest=!*TestIT*'"

test-job-IT:
  stage: test
  needs: [ "build-job", "test-job-unit" ]

  services:
    - postgres:latest

  variables:
    POSTGRES_DB: restaurant
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: admin

  script: "mvn test '-Dtest=*TestIT*' '-Dspring.profiles.active=gitlab'"

test-job-all:
  stage: test
  needs: [ "build-job", "test-job-unit", "test-job-IT" ]

  services:
    - postgres:latest

  variables:
    POSTGRES_DB: restaurant
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: admin

  script: "mvn test '-Dtest=*Test*' '-Dspring.profiles.active=gitlab'"
