image: maven:3-jdk-11

stages:
  - build
  - test

build-job-ubuntu:
  stage: build

  script: "mvn clean install -D=skipTests"

test-job-unit-ubuntu:
  stage: test
  needs: [ "build-job-ubuntu" ]

  script: "mvn test '-Dtest=!*TestIT*'"

test-job-IT-ubuntu:
  stage: test
  needs: [ "build-job-ubuntu", "test-job-unit-ubuntu" ]

  services:
    - postgres:latest

  variables:
    POSTGRES_DB: restaurant
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: admin

  script: "mvn test '-Dtest=*TestIT*' '-Dspring.profiles.active=gitlab'"

test-job-all-ubuntu:
  stage: test
  needs: [ "build-job-ubuntu", "test-job-unit-ubuntu", "test-job-IT-ubuntu" ]

  services:
    - postgres:latest

  variables:
    POSTGRES_DB: restaurant
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: admin

  script: "mvn test '-Dtest=*Test*' '-Dspring.profiles.active=gitlab'"
