name: CI workflow

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:

  build-ubuntu:
    name: Build with Maven on Ubuntu

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -D=skipTests

  build-macOS:
    name: Build with Maven on macOS

    runs-on: macos-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -D=skipTests

  build-windows:
    name: Build with Maven on Windows

    runs-on: windows-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -D=skipTests

  # UNIT TESTS
  test-unit-ubuntu:
    name: Unit tests with Maven on Ubuntu

    needs: [ build-ubuntu ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Unit tests with Maven
        run: mvn test '-Dtest=!*TestIT*'

  test-unit-macOS:
    name: Unit tests with Maven on MacOS

    needs: [ build-macOS ]

    runs-on: macos-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Unit tests with Maven
        run: mvn test '-Dtest=!*TestIT*'

  test-unit-windows:
    name: Unit tests with Maven on Windows

    needs: [ build-windows ]

    runs-on: windows-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Unit tests with Maven
        run: mvn test '-Dtest=!*TestIT*'

  # IT TESTS
  test-IT-ubuntu:
    name: Integration tests with Maven on Ubuntu

    runs-on: ubuntu-latest

    needs: [ build-ubuntu, test-unit-ubuntu, test-unit-macOS, test-unit-windows ]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: restaurant
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Integration tests with Maven
        run: mvn test '-Dtest=*TestIT*'

  #ALL  TESTS

  test-all-ubuntu:
    name: All tests with Maven on Ubuntu

    runs-on: ubuntu-latest

    needs: [ build-ubuntu, test-unit-ubuntu, test-IT-ubuntu ]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: restaurant
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: All tests with Maven
        run: mvn test