name: CI workflow

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=damman96_RestaurantManager

  #BUILD
  build-ubuntu:
    name: Build with Maven on Ubuntu

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -D=skipTests

  # UNIT TESTS
  test-unit-ubuntu:
    name: Unit tests with Maven on Ubuntu

    needs: [ build-ubuntu ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Unit tests with Maven
        run: mvn test '-Dtest=!*TestIT*'

  # IT TESTS
  test-IT-ubuntu:
    name: Integration tests with Maven on Ubuntu

    runs-on: ubuntu-latest

    needs: [ build-ubuntu, test-unit-ubuntu ]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: restaurant
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Integration tests with Maven
        run: mvn test '-Dtest=*TestIT*'

  #ALL  TESTS
  test-all-ubuntu:
    name: All tests with Maven on Ubuntu

    runs-on: ubuntu-latest

    needs: [ build-ubuntu, test-unit-ubuntu, test-IT-ubuntu ]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: restaurant
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: All tests with Maven
        run: mvn test '-Dtest=*Test*'